# Generated by Django 3.2.6 on 2022-01-03 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cashapp_TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Transaction type',
                'verbose_name_plural': 'Transaction Types',
                'db_table': 'cashapp_TransactionType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cashapp_CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank='true', null=True)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'cashapp_CashTransaction',
                'managed': True,
                'order_with_respect_to': 'amount',
            },
        ),
    ]
