# Generated by Django 3.2.6 on 2022-01-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=255, unique=True)),
                ('Balance', models.FloatField(blank='true', null=True)),
            ],
            options={
                'verbose_name': 'Transaction Account',
                'verbose_name_plural': 'Transaction Accounts',
                'db_table': 'transactionAccount',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='cashapp_cashtransaction',
            name='type',
        ),
        migrations.AddField(
            model_name='cashapp_cashtransaction',
            name='transactiontype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcash.cashapp_transactiontype'),
        ),
        migrations.AddField(
            model_name='cashapp_cashtransaction',
            name='transactionAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcash.transactionaccount'),
        ),
    ]
