# Generated by Django 3.2.6 on 2022-01-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcash', '0002_auto_20220104_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashapp_transactiontype',
            name='operation',
            field=models.IntegerField(blank='true', null=True),
        ),
    ]
