# Generated by Django 3.2.6 on 2022-01-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcash', '0003_cashapp_transactiontype_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashapp_cashtransaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cashapp_cashtransaction',
            name='transactionAccount',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='appcash.transactionaccount'),
        ),
        migrations.AlterField(
            model_name='cashapp_cashtransaction',
            name='transactiontype',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='appcash.cashapp_transactiontype'),
        ),
        migrations.AlterField(
            model_name='transactionaccount',
            name='Balance',
            field=models.FloatField(blank='true', default='0.00', null=True),
        ),
    ]
