# Generated by Django 3.2.6 on 2022-01-07 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcash', '0005_auto_20220106_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashapp_cashtransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='cashapp_closecash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('datecaptured', models.DateTimeField(auto_now_add=True)),
                ('accept_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcash.cashapp_cashtransaction')),
            ],
            options={
                'verbose_name': 'close Cash',
                'verbose_name_plural': 'close cash',
                'db_table': 'cashapp_closecash',
                'managed': True,
                'order_with_respect_to': 'datecaptured',
            },
        ),
    ]
